# Generated by Django 3.0 on 2019-12-10 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanningSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('session_error', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_path', models.CharField(max_length=1000)),
                ('file_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('name', models.CharField(max_length=500)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='uiapp.ScanningSession')),
            ],
        ),
    ]
