# Generated by Django 3.0 on 2019-12-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_id',
            field=models.CharField(max_length=255),
        ),
    ]
