# Generated by Django 3.0 on 2019-12-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiapp', '0002_auto_20191211_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanningsession',
            name='status',
            field=models.IntegerField(choices=[(0, 'in-process'), (1, 'successfully completed'), (2, 'completed with error')], default=0),
            preserve_default=False,
        ),
    ]
